{ '1': 
   { name: 'Margaret Chin',
     party: 'Democrat',
     district: '1',
     url: 'http://council.nyc.gov/d1/html/members/home.shtml',
     borough: 'Manhattan',
     photo_url: 'http://council.nyc.gov/d1//images/features/MC_headshot1.jpg',
     email: 'chin@council.nyc.gov' },
  '2': 
   { name: 'Rosie Mendez',
     party: 'Democrat',
     district: '2',
     url: 'http://council.nyc.gov/d2/html/members/home.shtml',
     borough: 'Manhattan',
     photo_url: 'http://council.nyc.gov/d2//image/Photos/d2mendez.jpg',
     email: 'Rmendez@council.nyc.gov ' },
  '3': 
   { name: 'Corey Johnson',
     party: 'Democrat',
     district: '3',
     url: 'http://council.nyc.gov/d3/html/members/home.shtml',
     borough: 'Manhattan',
     photo_url: 'http://council.nyc.gov/d3//images/features/District03_Johnson.jpg',
     email: 'District3@council.nyc.gov ' },
  '4': 
   { name: 'Daniel R. Garodnick',
     party: 'Democrat',
     district: '4',
     url: 'http://council.nyc.gov/d4/html/members/home.shtml',
     borough: 'Manhattan',
     photo_url: 'http://council.nyc.gov/d4//images/features/d4garodnick.jpg',
     email: '' },
  '5': 
   { name: 'Ben Kallos',
     party: 'Democrat',
     district: '5',
     url: 'http://council.nyc.gov/d5/html/members/home.shtml',
     borough: 'Manhattan',
     photo_url: 'http://council.nyc.gov/d5//images/features/District05_Kallos.jpg',
     email: 'BKallos@council.nyc.gov' },
  '6': 
   { name: 'Helen Rosenthal',
     party: 'Democrat',
     district: '6',
     url: 'http://council.nyc.gov/d6/html/members/home.shtml',
     borough: 'Manhattan',
     photo_url: 'http://council.nyc.gov/d6//images/features/District06Rosenthal.jpg',
     email: 'Helen@HelenRosenthal.com' },
  '7': 
   { name: 'Mark Levine',
     party: 'Democrat',
     district: '7',
     url: 'http://council.nyc.gov/d7/html/members/home.shtml',
     borough: 'Manhattan',
     photo_url: 'http://council.nyc.gov/d7//images/features/District07_Levine.jpg',
     email: 'District7@council.nyc.gov' },
  '8': 
   { name: 'Melissa Mark-Viverito',
     party: 'Democrat',
     district: '8',
     url: 'http://council.nyc.gov/d8/html/members/home.shtml',
     borough: 'Manhattan and Bronx',
     photo_url: 'http://council.nyc.gov/d8//images/melissa mark-viverito.jpg',
     email: 'mviverito@council.nyc.gov' },
  '9': 
   { name: 'Inez E. Dickens',
     party: 'Democrat',
     district: '9',
     url: 'http://council.nyc.gov/d9/html/members/home.shtml',
     borough: 'Manhattan',
     photo_url: 'http://council.nyc.gov/d9//images/features/d09ignizio.jpg',
     email: '' },
  '10': 
   { name: 'Ydanis Rodriguez',
     party: 'Democrat',
     district: '10',
     url: 'http://council.nyc.gov/d10/html/members/home.shtml',
     borough: 'Manhattan',
     photo_url: 'http://council.nyc.gov/d10/images/features/d10rodriguez.jpg',
     email: 'yrodriguez@council.nyc.gov' },
  '11': 
   { name: 'Andrew Cohen',
     party: 'Democrat',
     district: '11',
     url: 'http://council.nyc.gov/d11/html/members/home.shtml',
     borough: 'Bronx',
     photo_url: 'http://council.nyc.gov/d11/images/features/District11_Cohen.jpg',
     email: '' },
  '12': 
   { name: 'Andy King',
     party: 'Democrat',
     district: '12',
     url: 'http://council.nyc.gov/d12/html/members/home.shtml',
     borough: 'Bronx',
     photo_url: 'http://council.nyc.gov/d12/images/features/CMKING HS 220-311.jpg',
     email: 'Andy.King@council.nyc.gov' },
  '13': 
   { name: 'James Vacca',
     party: 'Democrat',
     district: '13',
     url: 'http://council.nyc.gov/d13/html/members/home.shtml',
     borough: 'Bronx',
     photo_url: 'http://council.nyc.gov/d13/images/features/d13vacca.jpg',
     email: 'jvacca@council.nyc.gov' },
  '14': 
   { name: 'Fernando Cabrera',
     party: 'Democrat',
     district: '14',
     url: 'http://council.nyc.gov/d14/html/members/home.shtml',
     borough: 'Bronx',
     photo_url: 'http://council.nyc.gov/d14/images/features/d14cabrera.jpg',
     email: '' },
  '15': 
   { name: 'Ritchie Torres',
     party: 'Democrat',
     district: '15',
     url: 'http://council.nyc.gov/d15/html/members/home.shtml',
     borough: 'Bronx',
     photo_url: 'http://council.nyc.gov/d15/images/features/District15_Torres2.jpg',
     email: '' },
  '16': 
   { name: 'Vanessa L Gibson',
     party: 'Democrat',
     district: '16',
     url: 'http://council.nyc.gov/d16/html/members/home.shtml',
     borough: 'Bronx',
     photo_url: 'http://council.nyc.gov/d16/images/features/district16_gibson.jpg',
     email: 'VGibson@council.nyc.gov' },
  '17': 
   { name: 'Maria del Carmen Arroyo',
     party: 'Democrat',
     district: '17',
     url: 'http://council.nyc.gov/d17/html/members/home.shtml',
     borough: 'Bronx',
     photo_url: 'http://council.nyc.gov/d17/images/features/d17arroyo.jpg',
     email: '' },
  '18': 
   { name: 'Annabel Palma',
     party: 'Democrat',
     district: '18',
     url: 'http://council.nyc.gov/d18/html/members/home.shtml',
     borough: 'Bronx',
     photo_url: 'http://council.nyc.gov/d18/images/features/d18palma.jpg',
     email: 'apalma@council.nyc.gov' },
  '19': 
   { name: 'Paul Vallone',
     party: 'Democrat',
     district: '19',
     url: 'http://council.nyc.gov/d19/html/members/home.shtml',
     borough: 'Queens',
     photo_url: 'http://council.nyc.gov/d19/images/features/District19_Vallone.jpg',
     email: 'district19@council.nyc.gov' },
  '20': 
   { name: 'Peter Koo',
     party: 'Democrat',
     district: '20',
     url: 'http://council.nyc.gov/d20/html/members/home.shtml',
     borough: 'Queens',
     photo_url: 'http://council.nyc.gov/d20/images/features/d20koo.jpg',
     email: 'pkoo@council.nyc.gov' },
  '21': 
   { name: 'Julissa Ferreras',
     party: 'Democrat',
     district: '21',
     url: 'http://council.nyc.gov/d21/html/members/home.shtml',
     borough: 'Queens',
     photo_url: 'http://council.nyc.gov/d21/images/HEADSHOT(new).jpg',
     email: 'jferreras@council.nyc.gov' },
  '22': 
   { name: 'Costa Constantinides',
     party: 'Democrat',
     district: '22',
     url: 'http://council.nyc.gov/d22/html/members/home.shtml',
     borough: 'Queens',
     photo_url: 'http://council.nyc.gov/d22/images/features/District22_Constantinides.jpg',
     email: 'costa@council.nyc.gov' },
  '23': 
   { name: 'Mark Weprin',
     party: 'Democrat',
     district: '23',
     url: 'http://council.nyc.gov/d23/html/members/home.shtml',
     borough: 'Queens',
     photo_url: 'http://council.nyc.gov/d23/images/District23_Weprin.jpg',
     email: 'MWeprin@Council.NYC.gov' },
  '24': 
   { name: 'Rory Lancman',
     party: 'Democrat',
     district: '24',
     url: 'http://council.nyc.gov/d24/html/members/home.shtml',
     borough: 'Queens',
     photo_url: 'http://council.nyc.gov/d24/images/features/District24_Lancman.jpg',
     email: 'RLancman@council.nyc.gov' },
  '25': 
   { name: 'Daniel Dromm',
     party: 'Democrat',
     district: '25',
     url: 'http://council.nyc.gov/d25/html/members/home.shtml',
     borough: 'Queens',
     photo_url: 'http://council.nyc.gov/d25/images/features/d25dromm.jpg',
     email: '' },
  '26': 
   { name: 'Jimmy Van Bramer',
     party: 'Democrat',
     district: '26',
     url: 'http://council.nyc.gov/d26/html/members/home.shtml',
     borough: 'Queens',
     photo_url: 'http://council.nyc.gov/d26/images/features/d26vanbramer.jpg',
     email: 'JVanBramer@council.nyc.gov' },
  '27': 
   { name: 'I. Daneek Miller',
     party: 'Democrat',
     district: '27',
     url: 'http://council.nyc.gov/d27/html/members/home.shtml',
     borough: 'Queens',
     photo_url: 'http://council.nyc.gov/d27/images/features/District27_Miller.jpg',
     email: 'District27@council.nyc.gov' },
  '28': 
   { name: 'Ruben Wills',
     party: 'Democrat',
     district: '28',
     url: 'http://council.nyc.gov/d28/html/members/home.shtml',
     borough: 'Queens',
     photo_url: 'http://council.nyc.gov/d28/images/features/WebSiteCM Wills 1.2.JPG',
     email: '' },
  '29': 
   { name: 'Karen Koslowitz',
     party: 'Democrat',
     district: '29',
     url: 'http://council.nyc.gov/d29/html/members/home.shtml',
     borough: 'Queens',
     photo_url: 'http://council.nyc.gov/d29/images/features/d29koslowitz.jpg',
     email: 'koslowitz@council.nyc.gov' },
  '30': 
   { name: 'Elizabeth Crowley',
     party: 'Democrat',
     district: '30',
     url: 'http://council.nyc.gov/d30/html/members/home.shtml',
     borough: 'Queens',
     photo_url: 'http://council.nyc.gov/d30/image/crowley_headshot_new.jpg',
     email: 'ecrowley@council.nyc.gov' },
  '31': 
   { name: 'Donovan Richards',
     party: ' Democrat',
     district: '31',
     url: 'http://council.nyc.gov/d31/html/members/home.shtml',
     borough: 'Queens',
     photo_url: 'http://council.nyc.gov/d31/images/cmrichardsheadshot.jpg',
     email: 'drichards@council.nyc.gov' },
  '32': 
   { name: 'Eric Ulrich',
     party: 'Republican',
     district: '32',
     url: 'http://council.nyc.gov/d32/html/members/home.shtml',
     borough: 'Queens',
     photo_url: 'http://council.nyc.gov/d32/images/ulrichheadshot.jpg',
     email: 'eulrich@council.nyc.gov' },
  '33': 
   { name: 'Stephen Levin',
     party: 'Democrat',
     district: '33',
     url: 'http://council.nyc.gov/d33/html/members/home.shtml',
     borough: 'Brooklyn',
     photo_url: 'http://council.nyc.gov/d33/images/features/d33levin.jpg',
     email: 'slevin@council.nyc.gov' },
  '34': 
   { name: 'Antonio Reynoso',
     party: 'Democrat',
     district: '34',
     url: 'http://council.nyc.gov/d34/html/members/home.shtml',
     borough: 'Brooklyn',
     photo_url: 'http://council.nyc.gov/d34/images/features/District34Reynoso.jpg',
     email: '' },
  '35': 
   { name: 'Laurie Cumbo',
     party: 'Democrat',
     district: '35',
     url: 'http://council.nyc.gov/d35/html/members/home.shtml',
     borough: 'Brooklyn',
     photo_url: 'http://council.nyc.gov/d35/images/features/District35_Cumbo1.jpg',
     email: 'M35@council.nyc.gov' },
  '36': 
   { name: 'Robert Cornegy',
     party: 'Democrat',
     district: '36',
     url: 'http://council.nyc.gov/d36/html/members/home.shtml',
     borough: 'Brooklyn',
     photo_url: 'http://council.nyc.gov/d36/images/features/District36_Cornegy.jpg',
     email: 'RCornegy@council.nyc.gov' },
  '37': 
   { name: 'Rafael Espinal',
     party: 'Democrat',
     district: '37',
     url: 'http://council.nyc.gov/d37/html/members/home.shtml',
     borough: 'Brooklyn',
     photo_url: 'http://council.nyc.gov/d37/images/features/District37_Espinal.jpg',
     email: 'REspinal@council.nyc.gov' },
  '38': 
   { name: 'Carlos Menchaca',
     party: 'Democrat',
     district: '38',
     url: 'http://council.nyc.gov/d38/html/members/home.shtml',
     borough: 'Brooklyn',
     photo_url: 'http://council.nyc.gov/d38/images/features/District38_Menchaca.jpg',
     email: '' },
  '39': 
   { name: 'Brad Lander',
     party: 'Democrat',
     district: '39',
     url: 'http://council.nyc.gov/d39/html/members/home.shtml',
     borough: 'Brooklyn',
     photo_url: 'http://council.nyc.gov/d39/images/features/d39lander.jpg',
     email: 'lander@council.nyc.gov' },
  '40': 
   { name: 'Mathieu Eugene',
     party: 'Democrat',
     district: '40',
     url: 'http://council.nyc.gov/d40/html/members/home.shtml',
     borough: 'Brooklyn',
     photo_url: 'http://council.nyc.gov/d40/images/features/d40eugene.jpg',
     email: 'mathieu.eugene@council.nyc.gov' },
  '41': 
   { name: 'Darlene Mealy',
     party: 'Democrat',
     district: '41',
     url: 'http://council.nyc.gov/d41/html/members/home.shtml',
     borough: 'Brooklyn',
     photo_url: 'http://council.nyc.gov/d41/images/features/d41mealy.jpg',
     email: '' },
  '42': 
   { name: 'Inez Barron',
     party: 'Democrat',
     district: '42',
     url: 'http://council.nyc.gov/d42/html/members/home.shtml',
     borough: 'Brooklyn',
     photo_url: 'http://council.nyc.gov/d42/images/features/District42_Barron.jpeg',
     email: '' },
  '43': 
   { name: 'Vincent Gentile',
     party: 'Democrat',
     district: '43',
     url: 'http://council.nyc.gov/d43/html/members/home.shtml',
     borough: 'Brooklyn',
     photo_url: 'http://council.nyc.gov/d43/images/features/d43gentile.jpg',
     email: 'vgentile@council.nyc.gov' },
  '44': 
   { name: 'David G. Greenfield',
     party: 'Democrat',
     district: '44',
     url: 'http://council.nyc.gov/d44/html/members/home.shtml',
     borough: 'Brooklyn',
     photo_url: 'http://council.nyc.gov/d44/images/features/d44greenfield.jpg',
     email: 'dgreenfield@council.nyc.gov' },
  '45': 
   { name: 'Jumaane D. Williams',
     party: 'Democrat',
     district: '45',
     url: 'http://council.nyc.gov/d45/html/members/home.shtml',
     borough: 'Brooklyn',
     photo_url: 'http://council.nyc.gov/d45/images/features/d45williams.jpg',
     email: 'JWilliams@council.nyc.gov' },
  '46': 
   { name: 'Alan Maisel',
     party: 'Democrat',
     district: '46',
     url: 'http://council.nyc.gov/d46/html/members/home.shtml',
     borough: 'Brooklyn',
     photo_url: 'http://council.nyc.gov/d46/images/features/District46_Maisel.jpg',
     email: 'AMaisel@council.nyc.gov' },
  '47': 
   { name: 'Mark Treyger',
     party: 'Democrat',
     district: '47',
     url: 'http://council.nyc.gov/d47/html/members/home.shtml',
     borough: 'Brooklyn',
     photo_url: 'http://council.nyc.gov/d47/images/features/District47_Treyger.jpeg',
     email: '' },
  '48': 
   { name: 'Chaim M. Deutsch',
     party: 'Democrat',
     district: '48',
     url: 'http://council.nyc.gov/d48/html/members/home.shtml',
     borough: 'Brooklyn',
     photo_url: 'http://council.nyc.gov/d48/images/features/District48_Deutsch3.jpg',
     email: 'cdeutsch@council.nyc.gov' },
  '49': 
   { name: 'Deborah Rose',
     party: 'Democrat',
     district: '49',
     url: 'http://council.nyc.gov/d49/html/members/home.shtml',
     borough: 'Staten Island',
     photo_url: 'http://council.nyc.gov/d49/images/features/d49rose.jpg',
     email: 'DROSE@Council.nyc.gov' },
  '50': 
   { name: 'Steven Matteo',
     party: 'Republican',
     district: '50',
     url: 'http://council.nyc.gov/d50/html/members/home.shtml',
     borough: 'Staten Island',
     photo_url: 'http://council.nyc.gov/d50/images/features/District50_Matteo.jpg',
     email: 'SMatteo@council.nyc.gov' },
  '51': 
   { name: 'Vincent Ignizio',
     party: 'Republican',
     district: '51',
     url: 'http://council.nyc.gov/d51/html/members/home.shtml',
     borough: 'Staten Island',
     photo_url: 'http://council.nyc.gov/d51/images/features/d51ignizio.jpg',
     email: 'vignizio@council.nyc.gov' } }