var models = require('./models')

var CouncilMember = models.CouncilMember
var mongoose = require('mongoose')

console.log("Inserting City Council Member Data")

{ name :'Maria del Carmen Arroyo',district_number:'17',borough :'Bronx', party: 'Democrat'},
 { name: 'Inez Barron',district_number:'42',borough :'Brooklyn', party: 'Democrat'},
 { name: 'Fernando Cabrera',district_number:'14',borough :'Bronx', party: 'Democrat'},
 { name: 'Margaret Chi'ndistrict_number:',1',borough :'Manhattan', party: 'Democrat'},
 { name: 'Andrew Cohen',district_number:'11',borough :'Bronx', party: 'Democrat'},
 { name: 'Robert Cornegy',district_number:'36',borough :'Brooklyn', party: 'Democrat'},
 { name: 'Costa Constantinides',district_number:'22',borough :',Queens', party: 'Democrat'},
 { name: 'Elizabeth Crowley',district_number:'30',borough :',Queens', party: 'Democrat'},
 { name: 'Laurie Cumbo',district_number:'35',borough :'Brooklyn', party: 'Democrat'},
 { name: 'Chaim M. Deutsch',district_number:'48',borough :'Brooklyn', party: 'Democrat'},
 { name: 'Inez E. Dickens'district_number:',9',borough :'Manhattan', party: 'Democrat'},
 { name: 'Daniel Dromm',district_number:'25',borough :',Queens', party: 'Democrat'},
 { name: 'Rafael Espinal',district_number:'37',borough :'Brooklyn', party: 'Democrat'},
 { name: 'Mathieu Eugene',district_number:'40',borough :'Brooklyn', party: 'Democrat'},
 { name: 'Julissa Ferreras',district_number:'21',borough :',Queens', party: 'Democrat'},
 { name: 'Daniel R. Garodnick',district_number:',4',borough :'Manhattan', party: 'Democrat'},
 { name: 'Vincent Gentile',district_number:'43',borough :'Brooklyn', party: 'Democrat'},
 { name: 'Vanessa L Gibson',district_number:'16',borough :'Bronx', party: 'Democrat'},
 { name: 'David G. Greenfield',district_number:'44',borough :'Brooklyn', party: 'Democrat'},
 { name: 'Vincent Ignizio'district_number:'51',borough :', Staten Island', party: 'Republican'},
 { name: 'Corey Johnson'district_number:',3',borough :'Manhattan', party: 'Democrat'},
 { name: 'Andy King',district_number:'12',borough :'Bronx', party: 'Democrat'},
 { name: 'Ben Kallos'district_number:',5',borough :'Manhattan', party: 'Democrat'},
 { name: 'Peter Koo',district_number:'20',borough :',Queens', party: 'Democrat'},
 { name: 'Karen Koslowitz',district_number:'29',borough :',Queens', party: 'Democrat'},
 { name: 'Rory Lancman',district_number:'24',borough :',Queens', party: 'Democrat'},
 { name: 'Brad Lander',district_number:'39',borough :'Brooklyn', party: 'Democrat'},
 { name: 'Stephen Levin',district_number:'33',borough :'Brooklyn', party: 'Democrat'},
 { name: 'Mark Levine',district_number:',7',borough :'Manhattan', party: 'Democrat'},
 { name: 'Alan Maisel',district_number:'46',borough :'Brooklyn', party: 'Democrat'},
 { name: 'Melissa Mark-Viverit'odistrict_number:',8',borough :'Manhattan and' borough :'Bronx', party: 'Democrat'},
 { name: 'Steven Matteo, 'district_number:'50',borough :', Staten Island', party: 'Republican'},
 { name: 'Darlene Mealy',district_number:'41',borough :'Brooklyn', party: 'Democrat'},
 { name: 'Carlos Menchaca',district_number:'38',borough :'Brooklyn', party: 'Democrat'},
 { name: 'Rosie Mende'zdistrict_number:',2',borough :'Manhattan', party: 'Democrat'},
 { name: 'I. Daneek Miller',district_number:'27',borough :',Queens', party: 'Democrat'},
 { name: 'Annabel Palma',district_number:'18',borough :'Bronx', party: 'Democrat'},
 { name: 'Antonio Reynoso',district_number:'34',borough :'Brooklyn', party: 'Democrat'},
 { name: 'Donovan Richards',district_number: '31',borough :',Queens ', party: 'Democrat'},
 { name: 'Ydanis Rodriguez',district_number:'10',borough :'Manhattan', party: 'Democrat'},
 { name: 'Deborah Rose',district_number:'49',borough :', Staten Island', party: 'Democrat'},
 { name: 'Helen Rosenthal', district_number:',6',borough :'Manhattan', party: 'Democrat'},
 { name: 'Ritchie Torres',district_number:'15',borough :'Bronx', party: 'Democrat'},
 { name: 'Mark Treyger',district_number:'47',borough :'Brooklyn', party: 'Democrat'},
 { name: 'Eric Ulrich', district_number: '32',borough :',Queen',party: 'Republican'},
 { name: 'James Vacca',district_number:'13',borough :'Bronx', party: 'Democrat'},
 { name: 'Paul Vallone',district_number:'19',borough :',Queens', party: 'Democrat'},
 { name: 'Jimmy Van Bramer',district_number:'26',borough :',Queens', party: 'Democrat'},
 { name: 'Mark Weprin',district_number:'23',borough :',Queens', party: 'Democrat'},
 { name: 'Jumaane D. Williams',district_number:'45',borough :'Brooklyn', party: 'Democrat'},
 { name: 'Ruben Wills',district_number:'28',borough :',Queens', party: 'Democrat'},

