[ {'Maria del Carmen Arroyo,,17,Bronx'},
 { 'Inez Barron,42,Brooklyn'},
 { 'Fernando Cabrera,14,Bronx'},
 { 'Margaret Chin,1,Manhattan'},
 { 'Andrew Cohen,11,Bronx'},
 { 'Robert Cornegy,36,Brooklyn'},
 { 'Costa Constantinides,22,Queens'},
 { 'Elizabeth Crowley,30,Queens'},
 { 'Laurie Cumbo,35,Brooklyn'},
 { 'Chaim M. Deutsch,48,Brooklyn'},
 { 'Inez E. Dickens,9,Manhattan'},
 { 'Daniel Dromm,25,Queens'},
 { 'Rafael Espinal,37,Brooklyn'},
 { 'Mathieu Eugene,40,Brooklyn'},
 { 'Julissa Ferreras,21,Queens'},
 { 'Daniel R. Garodnick,4,Manhattan'},
 { 'Vincent Gentile,43,Brooklyn'},
 { 'Vanessa L Gibson,16,Bronx'},
 { 'David G. Greenfield,44,Brooklyn'},
 { 'Vincent Ignizio51, Staten Island Republican'},
 { 'Corey Johnson,3,Manhattan'},
 { 'Andy King,12,Bronx'},
 { 'Ben Kallos,5,Manhattan'},
 { 'Peter Koo,20,Queens'},
 { 'Karen Koslowitz,29,Queens'},
 { 'Rory Lancman,24,Queens'},
 { 'Brad Lander,39,Brooklyn'},
 { 'Stephen Levin,33,Brooklyn'},
 { 'Mark Levine,7,Manhattan'},
 { 'Alan Maisel,46,Brooklyn'},
 { 'Melissa Mark-Viverito,8,Manhattan and Bronx'},
 { 'Steven Matteo50, Staten IslandRepublican'},
 { 'Darlene Mealy,41,Brooklyn'},
 { 'Carlos Menchaca,38,Brooklyn'},
 { 'Rosie Mendez,2,Manhattan'},
 { 'I. Daneek Miller,27,Queens'},
 { 'Annabel Palma,18,Bronx'},
 { 'Antonio Reynoso,34,Brooklyn'},
 { 'Donovan Richards,31,Queens '},
 { 'Ydanis Rodriguez,10,Manhattan'},
 { 'Deborah Rose49, Staten Island'},
 { 'Helen Rosenthal,6,Manhattan'},
 { 'Ritchie Torres,15,Bronx'},
 { 'Mark Treyger,47,Brooklyn'},
 { 'Eric Ulrich,32,QueensRepublican'},
 { 'James Vacca,13,Bronx'},
 { 'Paul Vallone,19,Queens'},
 { 'Jimmy Van Bramer,26,Queens'},
 { 'Mark Weprin,23,Queens'},
 { 'Jumaane D. Williams,45,Brooklyn'},
 { 'Ruben Wills,28,Queens'},
  ]
